batch_size: 64
epochs: 10
lr: 1e-4
num_classes: 9
finetune: False
layers_tune: 5
optimizer: 'Adam'
aug_data: True
num_workers: 4
model_type: 'resnet_e2e'
ckpt_name: 'resnet_e2e'
stored_features: False
